const MEDICAMENTOS = [
  "Abies Canadensis",
  "Abies Nigra",
  "Abrotanum",
  "Absinthium",
  "Acalypha Indica",
  "Acetic Acid.",
  "Aconitum Cammarum",
  "Aconitum Ferox",
  "Aconitum Lycotonum",
  "Aconitum Napellus",
  "Actća Spicata",
  "Ćsculus Glabra",
  "Ćsculus Hippocastanum",
  "Ćthusa Cynapium",
  "Agaricus Emeticus",
  "Agaricus Phalloides",
  "Agaricus Muscarius",
  "Agnus Castus",
  "Ailanthus",
  "Alcohol",
  "Aletris Farinosa",
  "Allium Cepa",
  "Allium Sativum",
  "Aloe Socotrina",
  "Alstonia Constricta",
  "Aluminium Metallicum",
  "Alumina Silicata",
  "Alumina",
  "Alumen",
  "Ammonium Benzoicum",
  "Ammonium Bromatum",
  "Ammonium Carbonicum",
  "Ammonium Causticum",
  "Ammonium Muriaticum",
  "Ambra Grisea",
  "Ambrosia Artemisić folia",
  "Amyl Nitrite",
  "Ammoniacum Gummi",
  "Amphisbśna",
  "Amygdalć Amarć Aqua",
  "Anacardium Occidentale",
  "Anacardium Orientale",
  "Anagallis Arvensis",
  "Anantherum Muricatum",
  "Angustura Vera",
  "Anilinum",
  "Anisum Stellatum",
  "Antimonium Arsenicosum",
  "Antimonium Crudum",
  "Antimonium Chloridum",
  "Antimonium Oxydatum",
  "Antimonium Sulph. Auratum",
  "Antimonium Tartaricum",
  "Anthemis Nobilis",
  "Anthracinum",
  "Anthrokokali",
  "Apium Graveolens",
  "Aphis Chenopodii glauci",
  "Apis Mellifica",
  "Apocynum Androsćmifolium",
  "Apocynum Cannabinum",
  "Apomorphium",
  "Aralia Racemosa",
  "Aranea Scinencia",
  "Aranea Diadema",
  "Argentum Cyanidum",
  "Argentum Metallicum",
  "Argentum Muriaticum",
  "Argentum Nitricum",
  "Arnica Montana",
  "Arsenicum Hydrogenisatum",
  "Arsenicum Iodatum",
  "Arsenicum Metallicum",
  "Arsenicum Nitricum",
  "Arsenicum Sulphuratum Flavum",
  "Arsenicum Sulphuratum Rubrum",
  "Arsenicum Album",
  "Artemisia Vulgaris",
  "Arum Dracontium",
  "Arum Italicum",
  "Arum Maculatum",
  "Arum Triphyllum",
  "Arundo Donax",
  "Arundo Mauritanica",
  "Asa Fśtida",
  "Asarum Europćum",
  "Asclepias Cornuti (Syriaca)",
  "Asclepias Tuberosa",
  "Asimina Triloba",
  "Asparagus Officinalis",
  "Astacus Fluviatilis",
  "Asterias Rubens",
  "Atropia Sulphurica",
  "Atropinium",
  "Aurum Arsenicum",
  "Aurum Iodatum",
  "Aurum Muriaticum Natronatum",
  "Aurum Muriaticum",
  "Aurum Sulphuratum",
  "Aurum Metallicum",
  "Badiaga",
  "Balsamum Peruvianum",
  "Baptisia Tinctoria",
  "Baryta Acetica",
  "Baryta Carbonica",
  "Baryta Iodata",
  "Baryta Muriatica",
  "Bartfelder (acid spring)",
  "Bellis Perennis",
  "Belladonna",
  "Benzoic Acid.",
  "Benzinum Nitricum",
  "Benzinum",
  "Berberis Vulgaris",
  "Bismuthum Oxidum",
  "Blatta Americana",
  "Blatta Orientalis",
  "Boletus Laricis",
  "Boracicum Acidum",
  "Borax",
  "Bothrops Lanceolatus",
  "Bovista",
  "Brachyglottis Repens",
  "Bromium",
  "Brucea Antidysenterica",
  "Bryonia Alba",
  "Bufo Sahytiensis",
  "Bufo Rana",
  "Cactus Grandiflorus",
  "Cadmium Sulphuratum",
  "Cahinca",
  "Cainca",
  "Cajuputum",
  "Caladium Seguinum",
  "Calcarea Acetica",
  "Calcarea Arsenica",
  "Calcarea Caustica",
  "Calcarea Fluorata",
  "Calcarea Iodata",
  "Calcarea Phosphorica",
  "Calcarea Sulphurica",
  "Calcarea Silicata",
  "Calcarea Carbonica",
  "Calendula Officinalis",
  "Calliandra Houstoni",
  "Calotropis Gigantea",
  "Caltha Palustris",
  "Camphora Officinarum",
  "Canchalagua",
  "Cannabis Indica",
  "Cannabis Sativa",
  "Cantharis",
  "Capsicum",
  "Carbolic Acid.",
  "Carbo Animalis",
  "Carboneum Hydrogenisatum",
  "Carboneum Oxygenisatum",
  "Carboneum Sulphuratum",
  "Carbo Vegetabilis",
  "Carduus Benedictus",
  "Carduus Marianus",
  "Carlsbad",
  "Cascarilla",
  "Castor Equi",
  "Castanea Vesca",
  "Castoreum",
  "Caulophyllum Thalictroides",
  "Causticum",
  "Ceanothus Americanus",
  "Cedron",
  "Cenchris Contortrix",
  "Centaurea Tagana",
  "Cereus Serpentaria",
  "Cereus Bonplandii",
  "Cetrararia Islandica",
  "Chamomilla",
  "Chelidonium Majus",
  "Chenopodium Anthelminticum",
  "Chenopodium Vulvaria",
  "Chenopodium Glauci Aphis",
  "Chimaphila Maculata",
  "Chimaphila Umbellata",
  "Chininum Arsenicosum",
  "Chininum Brom.",
  "Chininum Sulphuricum",
  "China Officinalis",
  "Chionanthus Virginica",
  "Chloroformium",
  "Chloralum",
  "Chlorum",
  "Cholesterinum",
  "Chromicum Acidum",
  "Chromicum Oxydatum",
  "Cicuta Virosa",
  "Cimicifuga Racemosa",
  "Cimex",
  "Cina",
  "Cinchona Boliviana",
  "Cinchonium Sulphuricum",
  "Cinnamomum",
  "Cinnabaris",
  "Cistus Canadensis",
  "Citricum Acidum",
  "Citrus Limonum",
  "Citrus Vulgaris",
  "Clematis Erecta",
  "Cobaltum",
  "Coccus Cacti",
  "Coca",
  "Cocainum Muriaticum",
  "Coccinella Septempunctata",
  "Cocculus Indicus",
  "Cochlearia Armoracia",
  "Codeinum",
  "Coffea Tosta",
  "Coffea Cruda",
  "Colchicum Autumnale",
  "Collinsonia Canadensis",
  "Colocynthis",
  "Colostrum",
  "Comocladia Dentata",
  "Conium Maculatum",
  "Cundurango",
  "Convolvulus Duartinus",
  "Convallaria Majalis",
  "Copaiva Officinalis",
  "Corallium Rubrum",
  "Coriaria Ruscifolia",
  "Cornus Florida",
  "Cornus Seriea",
  "Cornus Circinata",
  "Cotyledon Umbilicus",
  "Crocus Sativus",
  "Crotalus Cascavella",
  "Crotalus Horridus",
  "Croton Tiglium",
  "Cubeba Officinalis",
  "Culex Moscć",
  "Cuprum Aceticum",
  "Cuprum Arsenicosum",
  "Cuprum Nitricum",
  "Cuprum Sulphuricum",
  "Cuprum Metallicum",
  "Curare",
  "Cyclamen Europćum",
  "Cypripedium Pubescens",
  "Daphne Indica",
  "Derris Pinnata",
  "Digitalis Purpurea",
  "Dioscorea Villosa",
  "Dirca Palustris",
  "Dolichos Pruriens",
  "Doryphora",
  "Drosera Rotundifolia",
  "Duboisinum",
  "Dulcamara",
  "Echinacea Angustifolia",
  "Elaps Corallinus",
  "Elaterium",
  "Epigea Repens",
  "Equisetum Hyemale",
  "Erechthites Hieracifolia",
  "Erigeron Canadense",
  "Eryngium Aquaticum",
  "Ether",
  "Eucalyptus Globulus",
  "Eugenia Jambos",
  "Euonymus Europćus",
  "Eupatorium Perfoliatum",
  "Eupatorium Purpureum",
  "Euphorbium",
  "Euphrasia Officinalis",
  "Eupion",
  "Fagopyrum",
  "Ferrum Aceticum",
  "Ferrum Arsenicosum",
  "Ferrum Iodatum",
  "Ferrum Muriaticum",
  "Ferrum Magneticum",
  "Ferrum Phosphoricum",
  "Ferrum Picricum",
  "Ferrum Sulphuricum",
  "Ferrum Metallicum",
  "Filix Mas",
  "Fluoricum Acidum",
  "Formica Rufa",
  "Fragaria Vesca",
  "Gadus Morrhua",
  "Gallicum Acidum",
  "Gambogia",
  "Gelsemium Sempervirens",
  "Genista Tinctoria",
  "Gentiana Cruciata",
  "Gentiana Lutea",
  "Geranium Maculatum",
  "Gettisburg Water",
  "Ginseng",
  "Glanderine",
  "Glonoin",
  "Gnaphalium",
  "Gossypium Herbaceum",
  "Granatum Punica",
  "Graphites",
  "Gratiola Officinalis",
  "Grindelia Robusta",
  "Guaco",
  "Guaiacum",
  "Guano Australis",
  "Guarana",
  "Guarea",
  "Gymnocladus",
  "Hćmatoxylon",
  "Hamamelis Virginica",
  "Hecla Lava",
  "Hedeoma Pulegioides",
  "Helleborus Niger",
  "Heloderma",
  "Helonias Dioica",
  "Hepar Sulphuris Calcareum",
  "Hippomanes",
  "Hippozćnium",
  "Homarus",
  "Hura Braziliensis",
  "Hydrocyanicum Acidum",
  "Hydrastis Canadensis",
  "Hydrangea Arborescens",
  "Hydrocotyle Asiatica",
  "Hyoscyamus Niger",
  "Hypericum Perforatum",
  "Iberis Amara",
  "Ictodes Fśtida",
  "Ignatia Amara",
  "Illicium Anisatum",
  "Indium Metallicum",
  "Indigo",
  "Ingluvin",
  "Inula Helenium",
  "Iodium",
  "Iodoformum",
  "Ipecacuanha",
  "Ipomia Purpurea",
  "Iris Florentina",
  "Iris Fśtidissima",
  "Iris Germanica",
  "Iridium",
  "Iris Versicolor",
  "Jaborandi",
  "Jacaranda Caroba",
  "Jacaranda Gualandai",
  "Jalapa",
  "Jatropha Curcas",
  "Juglans Cinerea",
  "Juglans Regia",
  "Juncus Effusus",
  "Juniperus Virginiana",
  "Kali Aceticum",
  "Kali Arsenicosum",
  "Kali Bichromicum",
  "Kali Bromatum",
  "Kali Carbonicum",
  "Kali Chloricum",
  "Kali Cyanatum",
  "Kali Ferrocyanicum",
  "Kali Iodatum",
  "Kali Muriaticum",
  "Kali Manganicum",
  "Kali Nitricum",
  "Kali Oxalicum",
  "Kali Phosphoricum",
  "Kali Sulphuricum",
  "Kalmia Latifolia",
  "Kaolin",
  "Kino",
  "Kissingen",
  "Kreosotum",
  "Lac Caninum",
  "Lac Defloratum",
  "Lac Felinum",
  "Lachesis",
  "Lachnanthes Tinctoria",
  "Lactic Acid.",
  "Lactuca Virosa",
  "Lamium Album",
  "Lapis Albus",
  "Lappa Arctium",
  "Lappa Major",
  "Latrodectus Mactans",
  "Lathyrus Sativus",
  "Laurocerasus",
  "Lecithin",
  "Ledum Palustre",
  "Lemna Minor",
  "Lepidium Bonariense",
  "Leptandra Virginica",
  "Lilium Tigrinum",
  "Linum Cathar",
  "Lithium Muriaticum",
  "Lithium Carbonicum",
  "Lobelia Cardinalis",
  "Lobelia Syphilitica",
  "Lobelia Inflata",
  "Lupulus",
  "Lycopodium Clavatum",
  "Lycopersicum",
  "Lycopus Virginicus",
  "Lyssin (Hydrophobinum)",
  "Magnetis Polus Arcticus",
  "Magnetis Polus Australis",
  "Magnesia Carbonica",
  "Magnesia Muriatica",
  "Magnetis Poli. Ambo.",
  "Magnesia Phosphorica",
  "Magnesia Sulphurica",
  "Malandrinum",
  "Malaria Officinalis",
  "Mancinella (Hippomanes)",
  "Manganum Muriaticum",
  "Manganum",
  "Medorrhinum",
  "Melilotus Alba",
  "Menispermum",
  "Mentha Piperita",
  "Menyanthes",
  "Mephitis",
  "Mercurius Aceticus",
  "Mercurius Corrosivus",
  "Mercurius Cyanatus",
  "Mercurius Dulcis",
  "Mercurius Iodatus Flavus",
  "Mercurius Iodatus Ruber",
  "Mercurius Nitrosus",
  "Mercurius Prćcipitatus Ruber",
  "Mercurius Sulphuricus",
  "Mercurius Vivus",
  "Mercurialis",
  "Mezereum",
  "Millefolium",
  "Mitchella Repens",
  "Morphinum",
  "Moschus",
  "Muriaticum Acidum",
  "Murex",
  "Mygale Lasiodora",
  "Myosotis",
  "Myrica Cerifera",
  "Myristica Sebifera",
  "Myrtus Communis",
  "Naja Tripudia",
  "Naphthalin",
  "Narcotinum",
  "Natrum Arsenicatum",
  "Natrum Aceticum",
  "Natrum Carbonicum",
  "Natrum Hypochlorosum",
  "Natrum Muriaticum",
  "Natrum Nitricum",
  "Natrum Phosphoricum",
  "Natrum Sulphuricum",
  "Niccolum Sulph.",
  "Niccolum",
  "Nitricum Acidum",
  "Nitro Muriatic Acid.",
  "Nitri Spiritus Dulcis",
  "Nitrogenium Oxygenatum",
  "Nuphar Luteum",
  "Nux Juglans",
  "Nux Moschata",
  "Nux Vomica",
  "Nymphća Odorata",
  "Ocimum Canum",
  "Śnanthe Crocata",
  "Oleum Animale",
  "Oleum Jecoris Aselli",
  "Oleander",
  "Onosmodium",
  "Opium",
  "Origanum Majorana",
  "Osmium",
  "Ovinine",
  "Oxalicum Acidum",
  "Oxytropis Lamberti",
  "Ozone (Oxygenium)",
  "Pćonia Officinalis",
  "Palladium",
  "Paris Quadrifolia",
  "Pareira Brava",
  "Paullinia Pinnata",
  "Pediculus Capitis",
  "Penthorum",
  "Persica",
  "Petiveria",
  "Petroleum",
  "Petroselinum",
  "Phosphoricum Acidum",
  "Phallus Impudicus",
  "Phaseolus Nanus",
  "Phellandrium",
  "Phosphorus",
  "Physostigma",
  "Phytolacca Decandra",
  "Picricum Acidum",
  "Pimpinella Saxifraga",
  "Pinus Sylvestris",
  "Piper Methysticum",
  "Piper Nigrum",
  "Plantago Major",
  "Platinum Muriaticum",
  "Platinum Metallicum",
  "Plumbum Metallicum",
  "Plectranthus",
  "Plumbago Littoralis",
  "Podophyllum Peltatum",
  "Polygonum Hydropiperoides",
  "Populus Tremuloides",
  "Pothos Fśtidus",
  "Prunus Padus",
  "Prunus Spinosa",
  "Psorinum",
  "Ptelea Trifoliata",
  "Pulsatilla Nuttaliana",
  "Pulsatilla Nigricans",
  "Pulex Irritans",
  "Pyrogenium",
  "Pyrus Americana",
  "Radium",
  "Ranunculus Acris",
  "Ranunculus Bulbosus",
  "Ranunculus Sceleratus",
  "Raphanus",
  "Ratanhia",
  "Rheum",
  "Rhododendron",
  "Rhus aromatica",
  "Rhus Glabra",
  "Rhus Radicans",
  "Rhus Toxicodendron",
  "Rhus Venenata",
  "Robinia Pseudacacia",
  "Rumex Crispus",
  "Ruta Graveolens",
  "Sabadilla",
  "Sabal Serrulata",
  "Sabina",
  "Saccharum Lactis",
  "Saccharum Album",
  "Salicylicum Acidum",
  "Salix Niger",
  "Salamander",
  "Sambucus Nigra",
  "Sanguinaria Nitrica",
  "Sanguinaria Canadensis",
  "Sanicula Aqua",
  "Santoninum",
  "Sarracenia Purpurea",
  "Sarsaparilla",
  "Scutellaria Lateriflora",
  "Secale Cornutum",
  "Selenium",
  "Senecio Aureus",
  "Senega",
  "Senna",
  "Sepia",
  "Serpentaria",
  "Silicea",
  "Sinapis Alba",
  "Sinapis Nigra",
  "Solanum Mammosum",
  "Solanum Nigrum",
  "Solanum Oleraceum",
  "Solanum Tuberosum Ćgrotans",
  "Solidago Virg. aur.",
  "Spigelia Marilandica",
  "Spigelia Anthelmia",
  "Spiranthes",
  "Spongia Tosta",
  "Squilla hispanica",
  "Stachys Betonica",
  "Stannum Metallicum",
  "Staphysagria",
  "Stellaria Media",
  "Sticta Pulmonaria",
  "Stillingia Sylvatica",
  "Stramonium",
  "Strontium",
  "Strophanthus Hispidus",
  "Strychninum",
  "Sulphuricum Acidum",
  "Sulphur Iodatum",
  "Sulphur",
  "Sumbul",
  "Symphoricarpus Racemosus",
  "Symphytum Officinale",
  "Syphilinum",
  "Tabacum",
  "Tanacetum Vulgare",
  "Tanninum",
  "Taraxacum",
  "Tarentula Cubensis",
  "Tarentula Hispanica",
  "Tartaricum Acid.",
  "Taxus Baccata",
  "Tellurium",
  "Teplitz",
  "Terebinthina",
  "Teucrium Marum Verum",
  "Thallium",
  "Thea Sinensis",
  "Theridion",
  "Thlaspi Bursa Pastoris",
  "Thuja Occidentalis",
  "Tilia Europśa",
  "Tongo",
  "Trifolium Pratense",
  "Trillium Pendulum",
  "Triosteum Perfoliatum",
  "Trombidium Muscć Domesticć",
  "Tuberculinum",
  "Tussilago Fragrans",
  "Tussilago Petasites",
  "Upas Tiente",
  "Uranium Nitricum",
  "Urtica Urens",
  "Ustilago Maydis",
  "Uva Ursi",
  "Vaccininum",
  "Valeriana",
  "Variolinum",
  "Veratrum Viride",
  "Veratrum Album",
  "Verbascum Thapsus",
  "Vespa Crabro",
  "Viburnum Opulus",
  "Vinca Minor",
  "Viola Odorata",
  "Viola Tricolor",
  "Vipera",
  "Viscum Album",
  "Wiesbaden",
  "Wildbad",
  "Wyethia Helenioides",
  "Xanthoxylum Fraxineum",
  "Yucca",
  "Zincum Aceticum",
  "Zincum Cyanatum",
  "Zincum Muriaticum",
  "Zincum Oxydatum",
  "Zincum Sulphuricum",
  "Zincum Metallicum",
  "Zingiber",
  "Zizia Aurea",
];

const inventario = {};

document.addEventListener("DOMContentLoaded", () => {
  activarAutocomplete("nombre", "sugerencias-nombre");
  activarAutocomplete("despachoNombre", "sugerencias-despacho");
  setupForms();
  setupFiltroHistorial();
});

function activarAutocomplete(inputId, sugerenciasId) {
  const input = document.getElementById(inputId);
  const contenedor = document.getElementById(sugerenciasId);

  input.addEventListener("input", function () {
    const valor = this.value.trim().toLowerCase();
    contenedor.innerHTML = "";
    if (!valor) {
      contenedor.style.display = "none";
      return;
    }

    const filtrados = MEDICAMENTOS.filter((med) =>
      med.toLowerCase().includes(valor)
    ).slice(0, 20);

    if (!filtrados.length) {
      contenedor.style.display = "none";
      return;
    }

    filtrados.forEach((med) => {
      const item = document.createElement("div");
      item.textContent = med;
      item.addEventListener("click", () => {
        input.value = med;
        contenedor.innerHTML = "";
        contenedor.style.display = "none";
      });
      contenedor.appendChild(item);
    });

    contenedor.style.display = "block";
  });

  document.addEventListener("click", (e) => {
    if (!contenedor.contains(e.target) && e.target !== input) {
      contenedor.innerHTML = "";
      contenedor.style.display = "none";
    }
  });
}

// Formularios
function setupForms() {
  const inventarioForm = document.getElementById("inventarioForm");
  const despachoForm = document.getElementById("despachoForm");
  const tablaHistorial = document
    .getElementById("tablaHistorial")
    .querySelector("tbody");

  // Ingreso
  inventarioForm.addEventListener("submit", function (e) {
    e.preventDefault();

    const nombre = document.getElementById("nombre").value.trim();
    const presentacion = document.getElementById("presentacion").value;
    const difusion = document.getElementById("difusion").value;
    const cantidad = parseInt(document.getElementById("cantidad").value) || 0;
    const unidad = document.getElementById("unidad").value;
    const fecha = new Date().toLocaleString();

    if (!inventario[nombre]) {
      inventario[nombre] = { presentacion, difusion, unidad, cantidad: 0 };
    }
    inventario[nombre].cantidad += cantidad;

    agregarFilaHistorial(
      tablaHistorial,
      nombre,
      fecha,
      "Ingreso",
      `${cantidad} ${unidad}`,
      `${inventario[nombre].cantidad} ${unidad}`,
      "-",
      difusion
    );
    inventarioForm.reset();
  });

  // Despacho
  despachoForm.addEventListener("submit", function (e) {
    e.preventDefault();

    const nombre = document.getElementById("despachoNombre").value.trim();
    const cantidad =
      parseInt(document.getElementById("cantidadDespacho").value) || 0;
    const usuario = document.getElementById("usuarioDespacho").value.trim();
    const fecha = new Date().toLocaleString();

    if (!inventario[nombre]) {
      alert("Este medicamento no existe en el inventario.");
      return;
    }
    if (cantidad > inventario[nombre].cantidad) {
      alert("No hay suficiente cantidad disponible.");
      return;
    }

    inventario[nombre].cantidad -= cantidad;

    agregarFilaHistorial(
      tablaHistorial,
      nombre,
      fecha,
      "Despacho",
      `${cantidad} ${inventario[nombre].unidad}`,
      `${inventario[nombre].cantidad} ${inventario[nombre].unidad}`,
      usuario,
      inventario[nombre].difusion
    );
    despachoForm.reset();
  });
}

// Agregar fila con columna de Difusión
function agregarFilaHistorial(
  tbody,
  nombre,
  fecha,
  accion,
  cantidad,
  restante,
  usuario,
  difusion = "-"
) {
  const row = document.createElement("tr");
  row.innerHTML = `
    <td>${nombre}</td>
    <td>${fecha}</td>
    <td>${accion}</td>
    <td>${cantidad}</td>
    <td>${restante}</td>
    <td>${difusion}</td>
    <td>${usuario}</td>
  `;
  tbody.prepend(row);
}

// 🔎 Filtro para el historial (medicamento + cantidad restante)
function setupFiltroHistorial() {
  const filtroMed = document.getElementById("filtroHistorial");
  const filtroCant = document.getElementById("filtroCantidad");
  const filas = document.querySelector("#tablaHistorial tbody");

  function filtrar() {
    const valMed = filtroMed.value.trim().toLowerCase();
    const valCant = filtroCant.value.trim();
    const todasFilas = filas.querySelectorAll("tr");

    todasFilas.forEach((fila) => {
      const nombre = fila.cells[0].textContent.toLowerCase();
      const restante = parseFloat(fila.cells[4].textContent) || 0;

      const mostrar =
        nombre.includes(valMed) &&
        (valCant === "" || restante == parseFloat(valCant));

      fila.style.display = mostrar ? "" : "none";
    });
  }

  filtroMed.addEventListener("input", filtrar);
  filtroCant.addEventListener("input", filtrar);
}